### ISSUE TITLE
cannot install and import tensorflow 

### ISSUE THREAD

**Issue by vickykimani** [vickykimani/number-plate-recognition-system#1]
**_system information_**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
TensorFlow installed from (source or binary): source
TensorFlow version: 2.5
Python version: 3.10
Installed using virtualenv? pip? conda?: pip
Bazel version (if compiling from source): 4.2.0
CUDA/cuDNN version: 11.2

**_when I type "import tensorflow as tf" on a notebook on my machine I get this error_**

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py:58
     [56](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py?line=55)   sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_LOCAL)
---> [58](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py?line=57) from tensorflow.python.pywrap_tensorflow_internal import *
     [59](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py?line=58) from tensorflow.python.pywrap_tensorflow_internal import __version__

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:27
     [26](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py?line=25)         return _mod
---> [27](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py?line=26) _pywrap_tensorflow_internal = swig_import_helper()
     [28](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py?line=27) del swig_import_helper

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:22, in swig_import_helper()
     [21](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py?line=20) try:
---> [22](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py?line=21)     _mod = imp.load_module(
     [23](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py?line=22)         '_pywrap_tensorflow_internal', fp, pathname, description)
     [24](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py?line=23) finally:

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py:243, in load_module(name, file, filename, details)
    [242](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py?line=241)     else:
--> [243](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py?line=242)         return load_dynamic(name, filename, file)
    [244](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py?line=243) elif type_ == PKG_DIRECTORY:

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py:343, in load_dynamic(name, path, file)
    [341](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py?line=340) spec = importlib.machinery.ModuleSpec(
    [342](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py?line=341)     name=name, loader=loader, origin=path)
--> [343](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py?line=342) return _load(spec)

ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 0x0006): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Cell In [2], line 1
----> 1 import tensorflow as tf

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/__init__.py:24
     [21](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/__init__.py?line=20) from __future__ import print_function
     [23](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/__init__.py?line=22) # pylint: disable=g-bad-import-order
---> [24](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/__init__.py?line=23) from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     [25](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/__init__.py?line=24) # pylint: disable=wildcard-import
     [26](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/__init__.py?line=25) from tensorflow.tools.api.generator.api import *  # pylint: disable=redefined-builtin

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py:49
     [32](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py?line=31) # TODO(drpng): write up instructions for editing this file in a doc and point to
     [33](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py?line=32) # the doc instead.
     [34](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py?line=33) # If you want to edit this file to expose modules in public tensorflow API, you
   (...)
     [44](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py?line=43) # go/tf-wildcard-import
     [45](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py?line=44) # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     [47](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py?line=46) import numpy as np
---> [49](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py?line=48) from tensorflow.python import pywrap_tensorflow
     [51](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py?line=50) # Protocol buffers
     [52](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/__init__.py?line=51) from tensorflow.core.framework.graph_pb2 import *

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py:74
     [69](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py?line=68) except ImportError:
     [70](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py?line=69)   msg = """%s\n\nFailed to load the native TensorFlow runtime.\n
     [71](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py?line=70) See https://www.tensorflow.org/install/install_sources#common_installation_problems\n
     [72](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py?line=71) for some common reasons and solutions.  Include the entire stack trace
     [73](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py?line=72) above this error message when asking for help.""" % traceback.format_exc()
---> [74](file:///Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py?line=73)   raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 27, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 22, in swig_import_helper
    _mod = imp.load_module(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 0x0006): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**_what i got from this error is that I need the arm64 version of tensorflow since I'm using a mac m1. i then started the tensorflow download process again using homebrew:_**

brew install bazel

git clone https://github.com/tensorflow/tensorflow.git

./configure

WARNING: current bazel installation is not a release version.
Please specify the location of python. [Default is /Library/Frameworks/Python.framework/Versions/3.10/bin/python3]:   

Found possible Python library paths:
  /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Please input the desired Python library path to use.  Default is [/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: y
ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Could not find any cuda.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        '/usr'

_**what is the correct way to specify CUDA + cuDNN versions and paths?
any help would be greatly appreciated.
thanks in advance.**_

**Comment by vickykimani** [comment]
how to solve this problem:

https://www.youtube.com/watch?v=tGkZ9EARwzk&ab_channel=Algovibes

**Comment by vickykimani** [comment]
how to solve this problem:

https://www.youtube.com/watch?v=tGkZ9EARwzk&ab_channel=Algovibes
